# Generated by Django 5.2 on 2025-06-04 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_size_alter_order_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_processed'], name='orders_orde_is_proc_481304_idx'),
        ),
    ]
